id: P414E8BE4
initial_creation_type: ocr
source_metadata:
  volumes:
    7757306d66c14f4eafc57b4cb87d7dc1:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: དབུ་མ་རིན་པོ་ཆེའི་སྒྲོན་མ།
      total_pages: 1605
      volume_number: 57
